**Data Preprocessing**
---

**Importing Libraries**
---

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import warnings 
warnings.filterwarnings("ignore")

from google.colab import files
import io
import missingno
import seaborn as sns

ModuleNotFoundError: No module named 'pandas'

**Importing Data**
---

In [2]:
uploaded = files.upload()


Saving twitter_sentiment_data.csv to twitter_sentiment_data.csv


In [3]:
dataset =  pd.read_csv(io.BytesIO(uploaded['twitter_sentiment_data.csv']))

In [4]:
dataset.head()

sentiment  ...             tweetid
0         -1  ...  792927353886371840
1          1  ...  793124211518832641
2          1  ...  793124402388832256
3          1  ...  793124635873275904
4          2  ...  793125156185137153

[5 rows x 3 columns]

**basic data information**
---

In [5]:
dataset.shape


(43943, 3)

In [6]:
dataset.describe()


sentiment       tweetid
count  43943.000000  4.394300e+04
mean       0.853924  8.367966e+17
std        0.853543  8.568506e+16
min       -1.000000  5.926334e+17
25%        0.000000  7.970376e+17
50%        1.000000  8.402301e+17
75%        1.000000  9.020003e+17
max        2.000000  9.667024e+17

In [7]:
dataset.info() 


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 43943 entries, 0 to 43942
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype 
---  ------     --------------  ----- 
 0   sentiment  43943 non-null  int64 
 1   message    43943 non-null  object
 2   tweetid    43943 non-null  int64 
dtypes: int64(2), object(1)
memory usage: 1.0+ MB


In [8]:
dataset.isna().sum()

sentiment    0
message      0
tweetid      0
dtype: int64

There are no missing values.
Lets, Start with **Data Cleaning**...
---

In [9]:
# Cleaning the texts
import re
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


In [10]:
corpus = []
for i in range(0, 43942):
    review = re.sub('[^a-zA-Z]', ' ', dataset['message'][i])
    review = review.lower()
    review = review.split()
    ps = PorterStemmer()
    review = [ps.stem(word) for word in review if not word in set(stopwords.words('english'))]
    review = ' '.join(review)
    corpus.append(review)



In [19]:
len(corpus)

43942

I am using to use **Bag of word model for feature extraction**.
---

In [18]:
# Creating the Bag of Words model
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features = 5000)
x = cv.fit_transform(corpus).toarray()
y = dataset.iloc[0:43942, 0].values



[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


Splitting dataset
---

I am splitting dataset with 80/20 assumption.

i.e. 80% train and 20% test dataset. 

In [13]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.20, random_state = 0)
